services:
  totp:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - './instance/:/service/instance/'
    ports:
      - 5000:5000
      #- 5000:80
        #    hostname: onlyblogs
        # container_name: onlyblogs_service
    

