version: '3'

services:
  totp:
    stop_grace_period: 3s
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./instance/:/service/instance/
    ports:
      - 5000:80
    restart: unless-stopped
